SELECT LPAD( ' ' , 4*LEVEL-1)||XPLANO.CONTA_FILHO 
  FROM (
select PLANO.FLEX_VALUE CONTA_PAI , PLANO.HIERARCHY_LEVEL , PLANO.SUMMARY_FLAG  , FILHOS.flex_value CONTA_FILHO 
  from FND_FLEX_VALUES_VL PLANO
     , FND_FLEX_VALUE_CHILDREN_V FILHOS
WHERE FILHOS.parent_flex_value = PLANO.FLEX_VALUE     
  AND FILHOS.flex_value_set_id = PLANO.FLEX_VALUE_SET_ID
  AND PLANO.flex_value_set_id = 1018049 ) XPLANO
START WITH XPLANO.CONTA_PAI = '1'
CONNECT BY PRIOR XPLANO.CONTA_FILHO = XPLANO.CONTA_PAI
